# Generated by Django 4.2.7 on 2025-05-08 00:24

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=120, unique=True)),
                (
                    "description",
                    models.ImageField(
                        upload_to=questions.models.upload_question_image_location
                    ),
                ),
                ("time_limit", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=questions.models.upload_test_case_file_location
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["file"],
            },
        ),
        migrations.CreateModel(
            name="ExpectedOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=questions.models.upload_expected_output_file_location
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ["file"],
            },
        ),
    ]
