# Generated by Django 4.2.7 on 2025-05-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("time_limit", models.IntegerField(default=1)),
                (
                    "sample_input",
                    models.TextField(
                        blank=True, help_text="Sample input for the problem"
                    ),
                ),
                (
                    "sample_output",
                    models.TextField(
                        blank=True, help_text="Sample output for the problem"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField(help_text="Input for this test case")),
                (
                    "output_text",
                    models.TextField(help_text="Expected output for this test case"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
