# Generated by Django 4.2.7 on 2025-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
