# Generated by Django 4.2.7 on 2025-05-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="time_taken",
            field=models.IntegerField(default=0),
        ),
    ]
