# Generated by Django 4.2.7 on 2025-05-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="code_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("python2", "Python 2"),
                    ("python3", "Python 3"),
                    ("java", "Java"),
                ],
                max_length=10,
            ),
        ),
    ]
